name: node_fetch

on:
  push:
    paths:
      - ".github/workflows/subcribe_files_fetch.yml"
  #schedule:
    #- cron: "0 */6 * * *"
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  fetch-subcribe-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch subscription files
        uses: rxsweet/subs-fetcher@main
        with:
          #config: https://raw.githubusercontent.com/rxsweet/test/refs/heads/main/config.yaml
          config: ./config.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update subscription files
        uses: EndBug/add-and-commit@v9
        with:
          add: subs
          author_name: subscription-fetcher
          author_email: subscription-fetcher@users.noreply.github.com
          message: fetch done
