name: node_fetch

on:
  push:
    paths:
      - ".github/workflows/subcribe_files_fetch.yml"
  #schedule:
    #- cron: "0 */6 * * *"
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  fetch-subcribe-files:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch subscribe files
        uses: dongchengjie/subscription-fetcher@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: https://raw.githubusercontent.com/rxsweet/test/refs/heads/main/_config.yaml
          merged: subs/merged/merged.yaml
