name: test
on:
  workflow_dispatch:
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Prepare
        run: pip install requests

      - name: 执行任务 -1.Run get_trial.py
        run: |
          python test.py
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')update done"
          #git commit -m "${{ github.workflow }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
